version: 1.0.{build}-{branch}
image: Visual Studio 2017

branches:
    only:
      - master

init:
    # Good practise, because Windows line endings are different from Unix/Linux ones
    - cmd: git config --global core.autocrlf true

before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    # Display minimal restore text
    - cmd: dotnet restore ./api/src/src.csproj --verbosity m

build_script:
    # output will be in ./src/bin/debug/netcoreapp3.1/publish
    - cmd: dotnet publish ./api/src/src.csproj

artifacts:
    - path: '\api\src\bin\Debug\netcoreapp3.1\publish'
        name: SuggestionAPI
        type: WebDeployPackage
        
clone_depth: 1

test_script:
    # restore packages for our unit tests
    #- cmd: dotnet restore ./api/tests/tests.csproj --verbosity m
    # run the unit tests (requires changing into the test directory)
    #- cmd: cd /api/tests
    #- cmd: dotnet xunit

deploy: off
