#-----------------------#
# general configuration #
#-----------------------#

#version format
version: 1.0.{build}-{branch}
image: Visual Studio 2019

#branches to build
branches:
    only:
        - master

#---------------------------#
# environment configuration #
#---------------------------#
clone_depth: 1
init:
    - cmd: git config --global core.autocrlf true

#---------------------#
# build configuration #
#---------------------#
platform: Any CPU
configuration: Release

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore ./api/src/SuggestionAPI.csproj --verbosity m

build_script:
    - cmd: dotnet publish ./api/src/SuggestionAPI.csproj

#-------------------------#
# artifacts configuration #
#-------------------------#   

artifacts:
    - path: '\api\src\bin\Any CPU\Release\netcoreapp3.1\publish'
      name: SuggestionAPI
      type: WebDeployPackage    

test_script:
    # restore packages for our unit tests
    - cmd: dotnet restore ./api/tests/SuggestionAPI.Tests.csproj --verbosity m
    # run the unit tests (requires changing into the test directory)
    - cmd: cd /api/tests
    - cmd: dotnet xunit

#--------------------------#
# deployment configuration #
#--------------------------#   

deploy:
    - provider: Environment
      name: suggestion-api-production

